analytics-id: 
#Pages
pages:
  - {name: 'Episodes', url: 'episodes.html'}
  - {name: 'Patreon', url: '#'}
  - {name: 'Shop', url: '#'}
  - {name: 'GitHub', url: 'https://github.com/PandaSekh'}
  - {name: 'Get This Theme', url: 'https://github.com/PandaSekh/Jekyll-Podcaster'}

social:
  - {icon: 'instagram', type: "brand", link: '#'}
  - {icon: 'twitter', type: "brand", link: 'https://twitter.com/ArteLettura'}
  - {icon: 'facebook', type: "brand", link: '#'}
  - {icon: 'youtube', type: "brand", link: '#'}  
  - {icon: 'envelope', type: "solid", link: 'mailto:alessiofranceschi2@gmail.com'}
  - {icon: 'rss', type: "solid", link: "#"}

websites-podcast:
  - {name: 'Apple Podcast', link: '#'}
  - {name: 'Spotify', link: '#'}
  - {name: 'YouTube', link: '#'}
  - {name: 'Android', link: '#'}
  - {name: 'Spreaker', link: '#'}
  - {name: 'Google Podcast', link: '#'}
  - {name: 'Anchor', link: '#'}
  - {name: 'Castbox', link: '#'}
  - {name: 'Overcast', link: '#'}
  - {name: 'RadioPublic', link: '#'}
  - {name: 'Breaker', link: '#'}  
  - {name: 'RSS', link: '#'}

translate-date: true #See _includes/date.html to translate the months' name
shownotes: true

#Disqus
disqus:
  disqus_shortname: 